# Generated by Django 3.2.5 on 2022-08-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
