# Generated by Django 3.2.5 on 2022-08-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_empleado_employee_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_street', models.TextField()),
                ('address_number', models.IntegerField()),
                ('address_city', models.TextField()),
                ('address_province', models.TextField()),
                ('address_country', models.TextField()),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
    ]
