# Generated by Django 3.2.5 on 2022-08-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': True},
        ),
    ]
