# Generated by Django 3.2.5 on 2022-08-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_tarjeta_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
